apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: guestbook
            port:
              number: 80
